# Generated by Django 5.1.3 on 2024-11-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptno', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=10)),
                ('loc', models.TextField()),
            ],
        ),
    ]
