CREATE TABLE dept36 (
	deptno INT NOT NULL AUTO_INCREMENT,
	dname VARCHAR(50) NULL DEFAULT NULL,
	loc VARCHAR(50) NULL DEFAULT NULL,
	ordfile VARCHAR(50) NULL DEFAULT NULL,
	newfile VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (deptno)
)COLLATE='utf8mb4_general_ci';
