CREATE TABLE emp36 (
	empno INT NOT NULL AUTO_INCREMENT,
	ename VARCHAR(50) NULL DEFAULT NULL,
	pay INT NULL DEFAULT NULL,
	hiredate DATE NULL,
	ordfile VARCHAR(50) NULL DEFAULT NULL,
	newfile VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (empno)
)COLLATE='utf8mb4_general_ci';
