const os=require('os');
console.log(os.arch());
console.log(os.cpus().length);
console.log(os.homedir());
console.log(os.hostname());
console.log(os.platform());
console.log(os.tmpdir());
console.log(os.userInfo());
console.log(os.totalmem());
console.log(os.version());